### ISSUE TITLE
Support password hashing algorithms like Argon2,  PBKDF2,  scrypt,  bcrypt.

### ISSUE THREAD

**Issue by elonzh** [whyoleg/cryptography-kotlin#22]
Those algorithms are useful when developing multiplatform applications with ktor.

**Comment by Jadarma** [comment]
Came here looking for this. In my opinion PBKDF2 would be an amazing addition, as it would come in handy as a key derivation for the AES cypher.

**Comment by whyoleg** [comment]
Hey!
Thanks for the interest.
The story with PBKDF2 is rather straightforward (as all providers have support for it), we just need to design an API for PRF/KDF operations. So I will see how much work is needed here and will try to implement it in next release. Though, no dates, Im pretty busy right now with other stuff.

The story with other algorithms is not that easy - they are not supported by available providers, this means that they should be implemented from scratch. This will bring a precedent to the library for a cryptography operation implementation instead of usage of providers. There is no existing KMP libraries for this and wrapping some random external libraries is not an option.
So this should be properly designed, and most likely will take much more time, than adding PBKDF2, so for sure it will not be available soon.

Just a check, @elonzh, will it be enough for your use case to have just PBKDF2?

**Comment by elonzh** [comment]
A multiplatform PBKDF2 implementation looks good for me according to [Password Storage Cheat Sheet - OWASP Cheat Sheet Series](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html).

**Comment by elonzh** [comment]
Can we implement multiplatform cryptography algorithms by migrating the Java code of [the bouncycastle project](https://github.com/bcgit/bc-java/tree/main/core/src/main/java/org/bouncycastle/crypto/generators) to Kotlin?

Is that a good idea?

**Comment by whyoleg** [comment]
Preliminary API design (not final, just a POC): https://github.com/whyoleg/cryptography-kotlin/commit/c646bf41bbb64d1578043485b49ab43aa2416569
Also, it shows which algorithms (most likely) will be supported initially: PBKDF2, HKDF, DH, ECDH (availability of each algorithm per provider will be available later)

**Comment by eygraber** [comment]
@whyoleg any update on this?

**Comment by whyoleg** [comment]
PBKDF2 and ECDH are supported in main branch (published as 0.4.0-SNAPSHOT). HKDF and DH APIs were investigated, but probably will not be included in the following release as they are not really available in majority providers (even for Android+iOS cases).
I expect to do a release in ±month (by the end of September). Let's hope that everything will go as planned.

**Comment by whyoleg** [comment]
[0.4.0 was just released!](https://github.com/whyoleg/cryptography-kotlin/releases/tag/0.4.0)
[PBKDF2](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-p-b-k-d-f2/index.html), [ECDH](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-e-c-d-h/index.html) and [HKDF](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.algorithms/-h-k-d-f/index.html) are now available via [secret derivation](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.operations/-secret-derivation/index.html) and [shared secret derivation](https://whyoleg.github.io/cryptography-kotlin/api/cryptography-core/dev.whyoleg.cryptography.operations/-shared-secret-generator/index.html) APIs.
