### ISSUE TITLE
I have an error implementing cryptography-bom in the commonMain module

### ISSUE THREAD

**Issue by ArleyPereira** [whyoleg/cryptography-kotlin#27]
Project: Compose Multiplatform
Library version: 0.3.0
agp = "8.2.0"
kotlin = "1.9.22"
compose-bom = "2024.02.02"

I have an error implementing cryptography-bom in the commonMain module
cryptography-bom
cryptography-core
provider-jdk

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':composeApp:iosArm64CompilationDependenciesMetadata'.

![Screenshot at Mar 26 08-31-53](https://github.com/whyoleg/cryptography-kotlin/assets/47366406/8c9d9a19-1299-4174-9080-a3a7505fe2a8)

**Comment by whyoleg** [comment]
Hey!
BOM is JVM-only thing, so I would not expect it to work properly for `commonMain`. Or may be you have an example of working BOM in KMP projects?

I believe it could be easier to just use published `Version Catalog`: https://whyoleg.github.io/cryptography-kotlin/gradle-version-catalog/

**Comment by ngallazzi** [comment]
Same error for me: Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':composeApp:iosArm64CompilationDependenciesMetadata'.

**Comment by whyoleg** [comment]
@ngallazzi may be you know any `example of working BOM in KMP projects`? So I could investigate support for BOM outside of JVM?

**Comment by ArleyPereira** [comment]
Hello, an example of using BOM in KMP projects is Koin.

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }

https://insert-koin.io/docs/setup/koin

**Comment by whyoleg** [comment]
Okay, I've rechecked with the sample project from https://kmp.jetbrains.com and BOM is working fine with KMP. So `cryptography-bom` works as expected.
Though, the error comes from different place - looks like you are declaring dependency on `cryptography-provider-jdk` in common sourceSet. And because `provider-jdk` is supported only for `jvm` and `android` it doesn't work.
Gradle even shows something like this in an error message:
```
No matching variant of dev.whyoleg.cryptography:cryptography-provider-jdk:0.3.1 was found. The consumer was configured to find a library for use during 'kotlin-metadata', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64', attribute 'org.jetbrains.kotlin.platform.type' with value 'native' but:
...
```
Not very understandable error, yeah.

So, to solve the issue, you need to add dependencies on different providers for `jvmMain/androidMain` and `iosMain` sourceSets. Information about compatibility of different providers with targets can be found on [website](https://whyoleg.github.io/cryptography-kotlin/providers/#supported-primitives).

Also you can take a look on how [tests-publication](https://github.com/whyoleg/cryptography-kotlin/blob/458af35f62b2046b51d9e59c1afcd442f2a1a01e/tests-publication/build.gradle.kts#L54-L73) configures dependencies.

Still, looks like documentation is lacking some context. So I will create more self-describing samples for the following release, as well as add more documentation.

**Comment by Moozart** [comment]
Anyone has working example about dependency import?

**Comment by whyoleg** [comment]
To add library to android/iOS project you need to add dependency on `core` artefact for `commonMain` and provider dependency for `iosMain/androidMain` sourceSets, f.e:

```gradle
kotlin {
    sourceSets {
        commonMain.dependencies {
            implementation(project.dependencies.platform("dev.whyoleg.cryptography:cryptography-bom:0.3.1"))
            implementation("dev.whyoleg.cryptography:cryptography-core")
        }
        androidMain.dependencies {
            implementation("dev.whyoleg.cryptography:cryptography-provider-jdk")
        }
        iosMain.dependencies {
            implementation("dev.whyoleg.cryptography:cryptography-provider-openssl-prebuilt")
            // or `apple` provider
            // implementation("dev.whyoleg.cryptography:cryptography-provider-apple")
        }
    }
}
```

Does it solves your issue?
I will come-up with some of the examples on how to add library to projects, at least for mobile use-case, for upcoming release.

**Comment by whyoleg** [comment]
I think that the issue could be closed.
Additionally README was updated in https://github.com/whyoleg/cryptography-kotlin/pull/42 and now it better shows on how to correctly add dependencies
