### ISSUE TITLE
(IOS) - ECDSA not found

### ISSUE THREAD

**Issue by ngallazzi** [whyoleg/cryptography-kotlin#34]
```
Caused by: dev.whyoleg.cryptography.CryptographyAlgorithmNotFoundException:

Algorithm not found: dev.whyoleg.cryptography.algorithms.asymmetric.ECDSA

androidMain.dependencies {
    implementation("dev.whyoleg.cryptography:cryptography-provider-jdk:0.3.1")
    implementation("org.bouncycastle:bcpkix-jdk15on:1.68")
}

commonMain.dependencies {
     implementation("dev.whyoleg.cryptography:cryptography-core:0.3.1")
 }

 iosMain.dependencies {
    implementation("dev.whyoleg.cryptography:cryptography-provider-apple:0.3.1")
}
```
provider: `dev.whyoleg.cryptography:cryptography-provider-apple:0.3.1`

**Comment by whyoleg** [comment]
Hey!
As stated in [docs](https://whyoleg.github.io/cryptography-kotlin/providers/#supported-algorithms-per-provider), ECDSA is not yet supported with Apple provider, and for now it can be used only with openssl provider on native.
That's mostly because out-of-the-box (without CryptoKit) APIs for ECDSA there are limited and require more work to align it with other providers. In fact, I do want to improve this, though for now I have not a lot of time.

**Comment by whyoleg** [comment]
[0.4.0 was just released!](https://github.com/whyoleg/cryptography-kotlin/releases/tag/0.4.0)
ECDSA is now supported in Apple provider
