### ISSUE TITLE
Is there are any plans to support RSA with PKCS 1.5 padding for Openssl provider in future ?

### ISSUE THREAD

**Issue by deepak-mani-exa** [whyoleg/cryptography-kotlin#5]

**Comment by whyoleg** [comment]
Hey, yes, it's planned. Not only for openssl, but for JDK and WebCrypto providers.
Though, I have no time now to work on it, but I will try to find some time to add several algorithms for which there is exists already API, like RSASSA-PKCS-v1_5

**Comment by whyoleg** [comment]
Hey, just wanted to mention, that this is already implemented and works on all platforms in `dev` branch but blocked for now because of some issue with building documentation with `dokka` (will be fixed in dokka 1.9.0 release). I can't release without updating API documentation, as there are some breaking changes in API (mostly package changes) which I would like to highlight in API reference.
So, stay tuned, I'm hoping for `dokka` release by the end of August and short after that I will prepare release here
